[2025-04-23T01:43:56.734+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T01:10:00+00:00 [queued]>
[2025-04-23T01:43:56.755+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T01:10:00+00:00 [queued]>
[2025-04-23T01:43:56.757+0000] {taskinstance.py:2170} INFO - Starting attempt 3 of 2
[2025-04-23T01:43:56.863+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-23 01:10:00+00:00
[2025-04-23T01:43:56.876+0000] {standard_task_runner.py:60} INFO - Started process 221 to run task
[2025-04-23T01:43:56.880+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_ingestion_dag', 'load_to_snowflake', 'scheduled__2025-04-23T01:10:00+00:00', '--job-id', '321', '--raw', '--subdir', 'DAGS_FOLDER/mbta_ingestion_dag.py', '--cfg-path', '/tmp/tmp9wsc6gu_']
[2025-04-23T01:43:56.895+0000] {standard_task_runner.py:88} INFO - Job 321: Subtask load_to_snowflake
[2025-04-23T01:43:57.272+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T01:10:00+00:00 [running]> on host f6fee51db313
[2025-04-23T01:43:57.912+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_ingestion_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T01:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T01:10:00+00:00'
[2025-04-23T01:43:57.923+0000] {mbta_ingestion_dag.py:35} INFO - ðŸš€ Launching Kafka consumer to process and load data into Snowflake...
[2025-04-23T01:43:57.929+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T01:43:58.003+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T01:44:00.929+0000] {mbta_kafka_consumer.py:51} INFO - âœ… Connected to Snowflake successfully.
[2025-04-23T01:44:00.933+0000] {mbta_kafka_consumer.py:261} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-23T01:44:00.939+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-04-23T01:44:00.974+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-04-23T01:44:00.976+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-04-23T01:44:00.982+0000] {consumer.py:119} WARNING - group_id is None: disabling auto-commit.
[2025-04-23T01:44:00.985+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('mbta_alerts', 'mbta_routes', 'mbta_stops', 'mbta_vehicles', 'mbta_predictions', 'mbta_schedules', 'mbta_lines', 'mbta_facilities')
[2025-04-23T01:44:01.080+0000] {cluster.py:314} WARNING - Topic mbta_alerts is not available during auto-create initialization
[2025-04-23T01:44:01.093+0000] {cluster.py:314} WARNING - Topic mbta_facilities is not available during auto-create initialization
[2025-04-23T01:44:01.094+0000] {cluster.py:314} WARNING - Topic mbta_predictions is not available during auto-create initialization
[2025-04-23T01:44:01.097+0000] {cluster.py:314} WARNING - Topic mbta_lines is not available during auto-create initialization
[2025-04-23T01:44:01.097+0000] {cluster.py:314} WARNING - Topic mbta_schedules is not available during auto-create initialization
[2025-04-23T01:44:01.099+0000] {cluster.py:314} WARNING - Topic mbta_routes is not available during auto-create initialization
[2025-04-23T01:44:01.100+0000] {cluster.py:314} WARNING - Topic mbta_vehicles is not available during auto-create initialization
[2025-04-23T01:44:01.101+0000] {cluster.py:314} WARNING - Topic mbta_stops is not available during auto-create initialization
[2025-04-23T01:44:01.102+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-04-23T01:44:06.004+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-04-23T01:44:06.021+0000] {connection.py:718} INFO - closed
[2025-04-23T01:44:06.168+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-04-23T01:44:06.956+0000] {mbta_kafka_consumer.py:282} INFO - âœ… Snowflake Connection Closed.
[2025-04-23T01:44:06.968+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-23T01:44:07.074+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mbta_ingestion_dag, task_id=load_to_snowflake, execution_date=20250423T011000, start_date=20250423T014356, end_date=20250423T014407
[2025-04-23T01:44:07.226+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T01:44:07.316+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
