[2025-04-23T02:00:02.829+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T01:55:00+00:00 [queued]>
[2025-04-23T02:00:02.848+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T01:55:00+00:00 [queued]>
[2025-04-23T02:00:02.849+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-23T02:00:02.881+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): run_kafka_consumer> on 2025-04-23 01:55:00+00:00
[2025-04-23T02:00:02.888+0000] {standard_task_runner.py:60} INFO - Started process 203 to run task
[2025-04-23T02:00:02.892+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_kafka_consumer_dag', 'run_kafka_consumer', 'scheduled__2025-04-23T01:55:00+00:00', '--job-id', '342', '--raw', '--subdir', 'DAGS_FOLDER/mbta_kafka_consumer_dag.py', '--cfg-path', '/tmp/tmpjl7aybjy']
[2025-04-23T02:00:02.896+0000] {standard_task_runner.py:88} INFO - Job 342: Subtask run_kafka_consumer
[2025-04-23T02:00:02.947+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_kafka_consumer_dag.run_kafka_consumer scheduled__2025-04-23T01:55:00+00:00 [running]> on host 7e95a07730ab
[2025-04-23T02:00:03.088+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_kafka_consumer_dag' AIRFLOW_CTX_TASK_ID='run_kafka_consumer' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T01:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T01:55:00+00:00'
[2025-04-23T02:00:03.089+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T02:00:03.090+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T02:00:03.645+0000] {mbta_kafka_consumer.py:330} INFO - âœ… Connected to Snowflake successfully.
[2025-04-23T02:00:03.645+0000] {mbta_kafka_consumer.py:429} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-23T02:00:03.648+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-04-23T02:00:03.658+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.5', 9092)]>: Broker version identified as 2.6
[2025-04-23T02:00:03.659+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-04-23T02:00:03.660+0000] {consumer.py:119} WARNING - group_id is None: disabling auto-commit.
[2025-04-23T02:00:03.660+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('mbta_alerts', 'mbta_routes', 'mbta_stops', 'mbta_vehicles', 'mbta_predictions', 'mbta_schedules', 'mbta_lines', 'mbta_facilities')
[2025-04-23T02:00:03.676+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('mbta_lines', 0), ('mbta_schedules', 0), ('mbta_vehicles', 0), ('mbta_facilities', 0), ('mbta_predictions', 0), ('mbta_alerts', 0), ('mbta_stops', 0), ('mbta_routes', 0)]
[2025-04-23T02:00:03.678+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.5', 9092)]>: connecting to kafka:9092 [('172.18.0.5', 9092) IPv4]
[2025-04-23T02:00:03.679+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Connection complete.
[2025-04-23T02:00:03.679+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-04-23T02:00:08.666+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>: Closing connection. 
[2025-04-23T02:00:08.671+0000] {fetcher.py:735} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.5', 9092)]>
[2025-04-23T02:00:08.672+0000] {connection.py:718} INFO - closed
[2025-04-23T02:00:08.807+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-04-23T02:00:08.945+0000] {mbta_kafka_consumer.py:450} INFO - âœ… Snowflake Connection Closed.
[2025-04-23T02:00:08.946+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-23T02:00:08.968+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mbta_kafka_consumer_dag, task_id=run_kafka_consumer, execution_date=20250423T015500, start_date=20250423T020002, end_date=20250423T020008
[2025-04-23T02:00:09.018+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T02:00:09.036+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
