[2025-04-23T00:50:24.680+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T00:25:00+00:00 [queued]>
[2025-04-23T00:50:24.794+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T00:25:00+00:00 [queued]>
[2025-04-23T00:50:24.801+0000] {taskinstance.py:2170} INFO - Starting attempt 4 of 2
[2025-04-23T00:50:25.185+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-23 00:25:00+00:00
[2025-04-23T00:50:25.392+0000] {standard_task_runner.py:60} INFO - Started process 240 to run task
[2025-04-23T00:50:25.401+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_ingestion_dag', 'load_to_snowflake', 'scheduled__2025-04-23T00:25:00+00:00', '--job-id', '247', '--raw', '--subdir', 'DAGS_FOLDER/mbta_ingestion_dag.py', '--cfg-path', '/tmp/tmpo51h5mdb']
[2025-04-23T00:50:25.436+0000] {standard_task_runner.py:88} INFO - Job 247: Subtask load_to_snowflake
[2025-04-23T00:50:26.324+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T00:25:00+00:00 [running]> on host 577d99ce7fac
[2025-04-23T00:50:28.128+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_ingestion_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='4' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:25:00+00:00'
[2025-04-23T00:50:28.228+0000] {mbta_ingestion_dag.py:35} INFO - ðŸš€ Launching Kafka consumer to process and load data into Snowflake...
[2025-04-23T00:50:28.242+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T00:50:28.310+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T00:50:32.491+0000] {mbta_kafka_consumer.py:45} INFO - âœ… Connected to Snowflake successfully.
[2025-04-23T00:50:32.494+0000] {mbta_kafka_consumer.py:219} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-23T00:50:32.511+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-04-23T00:50:33.508+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-04-23T00:50:33.531+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-04-23T00:50:33.548+0000] {consumer.py:119} WARNING - group_id is None: disabling auto-commit.
[2025-04-23T00:50:33.550+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('mbta_alerts', 'mbta_routes', 'mbta_stops', 'mbta_vehicles', 'mbta_predictions')
[2025-04-23T00:50:33.731+0000] {cluster.py:317} ERROR - Topic mbta_alerts not found in cluster metadata
[2025-04-23T00:50:33.732+0000] {cluster.py:317} ERROR - Topic mbta_predictions not found in cluster metadata
[2025-04-23T00:50:33.734+0000] {cluster.py:317} ERROR - Topic mbta_routes not found in cluster metadata
[2025-04-23T00:50:33.736+0000] {cluster.py:317} ERROR - Topic mbta_vehicles not found in cluster metadata
[2025-04-23T00:50:33.737+0000] {cluster.py:317} ERROR - Topic mbta_stops not found in cluster metadata
[2025-04-23T00:50:33.738+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-04-23T00:50:38.622+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-04-23T00:50:38.656+0000] {connection.py:718} INFO - closed
[2025-04-23T00:50:38.810+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-04-23T00:50:39.032+0000] {mbta_kafka_consumer.py:240} INFO - âœ… Snowflake Connection Closed.
[2025-04-23T00:50:39.047+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-23T00:50:39.301+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mbta_ingestion_dag, task_id=load_to_snowflake, execution_date=20250423T002500, start_date=20250423T005024, end_date=20250423T005039
[2025-04-23T00:50:39.552+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T00:50:39.882+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
