[2025-04-23T00:50:38.739+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T00:40:00+00:00 [queued]>
[2025-04-23T00:50:38.752+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T00:40:00+00:00 [queued]>
[2025-04-23T00:50:38.752+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-04-23T00:50:38.766+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-23 00:40:00+00:00
[2025-04-23T00:50:38.793+0000] {standard_task_runner.py:60} INFO - Started process 256 to run task
[2025-04-23T00:50:38.808+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_ingestion_dag', 'load_to_snowflake', 'scheduled__2025-04-23T00:40:00+00:00', '--job-id', '255', '--raw', '--subdir', 'DAGS_FOLDER/mbta_ingestion_dag.py', '--cfg-path', '/tmp/tmphanb9x9d']
[2025-04-23T00:50:38.826+0000] {standard_task_runner.py:88} INFO - Job 255: Subtask load_to_snowflake
[2025-04-23T00:50:39.116+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-23T00:40:00+00:00 [running]> on host 577d99ce7fac
[2025-04-23T00:50:39.902+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_ingestion_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T00:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-23T00:40:00+00:00'
[2025-04-23T00:50:39.914+0000] {mbta_ingestion_dag.py:35} INFO - ðŸš€ Launching Kafka consumer to process and load data into Snowflake...
[2025-04-23T00:50:39.915+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-23T00:50:39.918+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-23T00:50:40.531+0000] {mbta_kafka_consumer.py:45} INFO - âœ… Connected to Snowflake successfully.
[2025-04-23T00:50:40.532+0000] {mbta_kafka_consumer.py:219} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-23T00:50:40.535+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-04-23T00:50:40.561+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.18.0.4', 9092)]>: Broker version identified as 2.6
[2025-04-23T00:50:40.562+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-04-23T00:50:40.564+0000] {consumer.py:119} WARNING - group_id is None: disabling auto-commit.
[2025-04-23T00:50:40.565+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('mbta_alerts', 'mbta_routes', 'mbta_stops', 'mbta_vehicles', 'mbta_predictions')
[2025-04-23T00:50:40.604+0000] {subscription_state.py:254} INFO - Updated partition assignment: [('mbta_routes', 0), ('mbta_predictions', 0), ('mbta_vehicles', 0), ('mbta_stops', 0), ('mbta_alerts', 0)]
[2025-04-23T00:50:40.607+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connecting> [IPv4 ('172.18.0.4', 9092)]>: connecting to kafka:9092 [('172.18.0.4', 9092) IPv4]
[2025-04-23T00:50:40.607+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Connection complete.
[2025-04-23T00:50:40.608+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-04-23T00:50:45.569+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>: Closing connection. 
[2025-04-23T00:50:45.572+0000] {fetcher.py:735} INFO - Fetch to node 1 failed: Cancelled: <BrokerConnection client_id=kafka-python-2.1.5, node_id=1 host=kafka:9092 <connected> [IPv4 ('172.18.0.4', 9092)]>
[2025-04-23T00:50:45.572+0000] {connection.py:718} INFO - closed
[2025-04-23T00:50:45.701+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-04-23T00:50:45.845+0000] {mbta_kafka_consumer.py:240} INFO - âœ… Snowflake Connection Closed.
[2025-04-23T00:50:45.847+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-23T00:50:45.913+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mbta_ingestion_dag, task_id=load_to_snowflake, execution_date=20250423T004000, start_date=20250423T005038, end_date=20250423T005045
[2025-04-23T00:50:46.059+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-23T00:50:46.098+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
