[2025-04-24T03:20:59.293+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-24T02:25:00+00:00 [queued]>
[2025-04-24T03:20:59.344+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-24T02:25:00+00:00 [queued]>
[2025-04-24T03:20:59.345+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 2
[2025-04-24T03:20:59.497+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): load_to_snowflake> on 2025-04-24 02:25:00+00:00
[2025-04-24T03:20:59.578+0000] {standard_task_runner.py:60} INFO - Started process 224 to run task
[2025-04-24T03:20:59.600+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'mbta_ingestion_dag', 'load_to_snowflake', 'scheduled__2025-04-24T02:25:00+00:00', '--job-id', '883', '--raw', '--subdir', 'DAGS_FOLDER/mbta_ingestion_dag.py', '--cfg-path', '/tmp/tmpbk9i0ktw']
[2025-04-24T03:20:59.624+0000] {standard_task_runner.py:88} INFO - Job 883: Subtask load_to_snowflake
[2025-04-24T03:21:00.482+0000] {task_command.py:423} INFO - Running <TaskInstance: mbta_ingestion_dag.load_to_snowflake scheduled__2025-04-24T02:25:00+00:00 [running]> on host 120454fa5f04
[2025-04-24T03:21:01.123+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='mbta_ingestion_dag' AIRFLOW_CTX_TASK_ID='load_to_snowflake' AIRFLOW_CTX_EXECUTION_DATE='2025-04-24T02:25:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-24T02:25:00+00:00'
[2025-04-24T03:21:01.127+0000] {mbta_ingestion_dag.py:35} INFO - ðŸš€ Launching Kafka consumer to process and load data into Snowflake...
[2025-04-24T03:21:01.130+0000] {connection.py:370} INFO - Snowflake Connector for Python Version: 3.6.0, Python Version: 3.9.18, Platform: Linux-6.10.14-linuxkit-aarch64-with-glibc2.36
[2025-04-24T03:21:01.137+0000] {connection.py:1171} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2025-04-24T03:21:02.045+0000] {mbta_kafka_consumer.py:52} INFO - âœ… Connected to Snowflake successfully.
[2025-04-24T03:21:02.053+0000] {mbta_kafka_consumer.py:266} INFO - ðŸš€ Starting MBTA Kafka Consumer...
[2025-04-24T03:21:02.064+0000] {conn.py:395} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connecting> [IPv4 ('172.19.0.2', 9092)]>: connecting to kafka:9092 [('172.19.0.2', 9092) IPv4]
[2025-04-24T03:21:02.459+0000] {conn.py:615} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <checking_api_versions_recv> [IPv4 ('172.19.0.2', 9092)]>: Broker version identified as 2.6
[2025-04-24T03:21:02.467+0000] {conn.py:456} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.19.0.2', 9092)]>: Connection complete.
[2025-04-24T03:21:02.540+0000] {consumer.py:119} WARNING - group_id is None: disabling auto-commit.
[2025-04-24T03:21:02.543+0000] {subscription_state.py:182} INFO - Updating subscribed topics to: ('mbta_alerts', 'mbta_routes', 'mbta_stops', 'mbta_vehicles', 'mbta_predictions', 'mbta_schedules', 'mbta_lines', 'mbta_facilities')
[2025-04-24T03:21:02.667+0000] {cluster.py:317} ERROR - Topic mbta_alerts not found in cluster metadata
[2025-04-24T03:21:02.671+0000] {cluster.py:317} ERROR - Topic mbta_facilities not found in cluster metadata
[2025-04-24T03:21:02.672+0000] {cluster.py:317} ERROR - Topic mbta_predictions not found in cluster metadata
[2025-04-24T03:21:02.673+0000] {cluster.py:317} ERROR - Topic mbta_schedules not found in cluster metadata
[2025-04-24T03:21:02.673+0000] {cluster.py:317} ERROR - Topic mbta_routes not found in cluster metadata
[2025-04-24T03:21:02.673+0000] {cluster.py:317} ERROR - Topic mbta_vehicles not found in cluster metadata
[2025-04-24T03:21:02.674+0000] {cluster.py:317} ERROR - Topic mbta_stops not found in cluster metadata
[2025-04-24T03:21:02.675+0000] {cluster.py:314} WARNING - Topic mbta_lines is not available during auto-create initialization
[2025-04-24T03:21:02.676+0000] {subscription_state.py:254} INFO - Updated partition assignment: []
[2025-04-24T03:21:32.581+0000] {conn.py:936} INFO - <BrokerConnection client_id=kafka-python-2.1.5, node_id=bootstrap-0 host=kafka:9092 <connected> [IPv4 ('172.19.0.2', 9092)]>: Closing connection. 
[2025-04-24T03:21:32.615+0000] {connection.py:718} INFO - closed
[2025-04-24T03:21:32.849+0000] {connection.py:724} INFO - No async queries seem to be running, deleting session
[2025-04-24T03:21:33.006+0000] {mbta_kafka_consumer.py:287} INFO - âœ… Snowflake Connection Closed.
[2025-04-24T03:21:33.025+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-04-24T03:21:33.246+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=mbta_ingestion_dag, task_id=load_to_snowflake, execution_date=20250424T022500, start_date=20250424T032059, end_date=20250424T032133
[2025-04-24T03:21:33.457+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-04-24T03:21:33.617+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
